version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
  kafka:
    build: .
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 47.97.243.10
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: ""
      KAFKA_SSL_KEY_PASSWORD: ""
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ""
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN,SCRAM-SHA-256,SCRAM-SHA-512"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/kafka.keystore.jks:/opt/bitnami/kafka/conf/certs/kafka.keystore.jks:ro
      - ./certs/kafka.truststore.jks:/opt/bitnami/kafka/conf/certs/kafka.truststore.jks:ro

volumes:
  zookeeper_data:
    driver: local
  zookeeper_datalog:
    driver: local
  kafka_data:
    driver: local
